In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr=np.ones(10)
arr[5]=0
print(arr)

[1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]


In [11]:
arr5=np.ones(10)*5
print(arr5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
arr10to50=np.arange(10,51)
print(arr10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
arr_even_10to50 = np.arange(10,51,2)
print(arr_even_10to50)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [35]:
threebythree_matrix = np.array(3, 3).arange(0,9)
arr

TypeError: Cannot interpret '3' as a data type

In [31]:
arridentity = np.eye(3, 3)
print(arridentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
arr = np.random.randint(0, 9, 9)
arr
arr.reshape(3,3)

array([[1, 7, 8],
       [8, 2, 8],
       [4, 2, 6]])

In [65]:
arr = np.random.randint(0, 9, (3,3))
arr


array([[5, 8, 0],
       [1, 4, 1],
       [3, 6, 1]])

In [112]:
a=np.random.rand(5,5)
print(a)

[[0.16660085 0.82667038 0.38729194 0.9928496  0.96292863]
 [0.11972773 0.98326849 0.52463936 0.36871017 0.29773879]
 [0.17801348 0.97611243 0.19858732 0.43043165 0.42895693]
 [0.26344646 0.54382787 0.40584371 0.42203475 0.27027133]
 [0.2310744  0.22324562 0.083628   0.28981715 0.07514515]]


In [116]:
a=np.random.randn(2,2)
print(a)

[[ 0.37635414 -1.01630587]
 [-0.53909451  0.88264224]]


In [118]:
a = np.random.rand()
a

0.5279897378448708

In [126]:
arr =np.random.randn(25)
print(arr)
a=np.std(arr)
a

[-0.16150751  0.18636413  0.8817893  -0.50077734 -0.9792142  -0.60810117
 -1.62307471 -0.59304475  0.05664009  0.77498749  0.58447326  0.08349571
  0.60374399 -0.19412135  0.70009418  0.05926385 -1.04673472 -0.80392033
 -0.31762949 -0.22786815 -0.06161365  0.88420964  0.56367109 -0.95897584
 -0.18037892]


0.6594240145886252

In [148]:
import numpy as np

# Given numpy array
data = np.array([-0.16150751, 0.18636413, 0.8817893, -0.50077734, -0.9792142, -0.60810117,
                 -1.62307471, -0.59304475, 0.05664009, 0.77498749, 0.58447326, 0.08349571,
                 0.60374399, -0.19412135, 0.70009418, 0.05926385, -1.04673472, -0.80392033,
                 -0.31762949, -0.22786815, -0.06161365, 0.88420964, 0.56367109, -0.95897584,
                 -0.18037892])

# Population standard deviation
population_std_dev = np.std(data)

# Sample standard deviation
sample_std_dev = np.std(data, ddof=1)

population_std_dev, sample_std_dev


(0.6594240146170585, 0.6730218166455788)

In [132]:
mean = sum(arr)/len(arr)

In [134]:
mean

-0.115129176424768

In [142]:
arr -= mean
variance = ((sum(arr)-mean)**2)/len(arr)
variance

0.305388916168213

In [144]:
a**2

0.4348400310161794

In [215]:
arr = np.arange(0.01,1.01,0.01)

In [217]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [219]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [221]:
arr.reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [225]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [227]:
mat=np.array(np.arange(1,26))

In [233]:
print(mat)

mat.reshape(5,5)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [241]:
mat=mat.reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [243]:
mat[2][1:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [251]:
mat[2][1:], mat[3][1:],mat[4][1:]

(array([12, 13, 14, 15]), array([17, 18, 19, 20]), array([22, 23, 24, 25]))

In [253]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [255]:
mat[3][-1]

20

In [257]:
mat[0][1],mat[1][1],mat[2][1]

(2, 7, 12)

In [259]:
mat[4]

array([21, 22, 23, 24, 25])

In [261]:
mat[3], mat[4]

(array([16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25]))

In [275]:
np.sum(mat)

325

In [273]:
mat.sum()

325

In [267]:
np.std(mat)

7.211102550927978

In [277]:
mat.sum(0)

array([55, 60, 65, 70, 75])

In [279]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [3]:
import numpy as np

In [5]:
arr=np.array([11,234,123,134,124,123,4673567,234234,234324])

In [7]:
arr

array([     11,     234,     123,     134,     124,     123, 4673567,
        234234,  234324])

In [11]:
arr.sort(reverse=True)

TypeError: sort() got an unexpected keyword argument 'reverse'

In [13]:
arr[::-1]

array([ 234324,  234234, 4673567,     123,     124,     134,     123,
           234,      11])

In [43]:
arr = np.array([10, 20, 0, 0, 40, 0])
for i in arr:
    if i==0:
        continue
    print(i)

10
20
40


In [47]:
np.where(arr!=0)

(array([0, 1, 4], dtype=int64),)

In [71]:
arr=np.random.random((10,10))


In [75]:
arr

array([[0.13081486, 0.06996434, 0.45171647, 0.27057426, 0.2197388 ,
        0.20921728, 0.53398094, 0.7351938 , 0.69755038, 0.08046751],
       [0.54483283, 0.38109137, 0.53832656, 0.99521143, 0.54788739,
        0.59945776, 0.06223804, 0.78561138, 0.04724163, 0.22281197],
       [0.90058273, 0.78393557, 0.46476372, 0.78932236, 0.14793593,
        0.083278  , 0.93206936, 0.22830795, 0.42008759, 0.90086234],
       [0.88491525, 0.25490781, 0.12799419, 0.40957174, 0.33785635,
        0.30896852, 0.47058287, 0.34906413, 0.59655626, 0.84394838],
       [0.07124828, 0.47619861, 0.92150803, 0.41294405, 0.31132005,
        0.7484902 , 0.36837098, 0.0171708 , 0.82348735, 0.17354491],
       [0.97481609, 0.17706922, 0.72716386, 0.21315823, 0.15734427,
        0.46480435, 0.42617868, 0.96060892, 0.45244277, 0.71727296],
       [0.25646367, 0.3149391 , 0.69036491, 0.93554846, 0.70098561,
        0.32737869, 0.02827598, 0.87060337, 0.38773222, 0.30802362],
       [0.8528665 , 0.67228528, 0.2695715

In [79]:
np.max(arr)

0.9952114327738311

In [87]:
arr = np.random.randint(1,100,size=(10,10))
arr

array([[74, 85, 32, 41, 17, 34, 77, 21, 89, 58],
       [50, 92, 73, 97, 41, 33, 74, 78, 83, 12],
       [22, 21, 74, 31, 10, 44, 38,  7, 89, 40],
       [81, 88, 48, 71, 88, 89, 16,  3, 85, 63],
       [ 3, 56, 28, 52, 87, 94, 20, 34, 19, 21],
       [ 9, 80, 51,  2, 23, 93, 74, 48, 62, 68],
       [69, 61, 98, 46, 30, 30, 28, 41, 43, 31],
       [25, 22,  9, 57, 96, 15, 87, 64, 55, 72],
       [75, 48, 69, 75, 40, 95, 89, 20, 71, 55],
       [84, 30, 56, 10, 26, 54, 84, 82, 32, 63]])

In [89]:
np.max(arr)

98

In [91]:
np.min(arr)

2

In [97]:
ex25 = np.random.randint(1,100,(10,10))

ex25

array([[68,  6, 94, 97, 13, 40, 52, 74, 32, 31],
       [22,  8, 71, 18, 76, 52, 26, 21, 78, 80],
       [ 8, 24, 49,  2, 23, 43, 13, 88, 50, 45],
       [50, 63, 95, 46, 25, 41,  2, 15, 10, 63],
       [19, 32, 75, 86, 88, 73, 19, 86, 78, 12],
       [96, 48, 69, 70,  2, 96, 26, 87,  5, 34],
       [75, 58, 95, 89, 70, 97, 25, 32, 73, 23],
       [19, 24, 64, 84,  7, 76, 52, 71, 81, 97],
       [53, 89, 28, 59, 11, 60, 82, 19, 19, 90],
       [48, 47, 26,  6, 61, 45, 65, 60, 57, 73]])

In [101]:
ex25[0]=1

In [103]:
ex25

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [22,  8, 71, 18, 76, 52, 26, 21, 78, 80],
       [ 8, 24, 49,  2, 23, 43, 13, 88, 50, 45],
       [50, 63, 95, 46, 25, 41,  2, 15, 10, 63],
       [19, 32, 75, 86, 88, 73, 19, 86, 78, 12],
       [96, 48, 69, 70,  2, 96, 26, 87,  5, 34],
       [75, 58, 95, 89, 70, 97, 25, 32, 73, 23],
       [19, 24, 64, 84,  7, 76, 52, 71, 81, 97],
       [53, 89, 28, 59, 11, 60, 82, 19, 19, 90],
       [48, 47, 26,  6, 61, 45, 65, 60, 57, 73]])

In [105]:
ex25[-1]=1

In [107]:

ex25

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [22,  8, 71, 18, 76, 52, 26, 21, 78, 80],
       [ 8, 24, 49,  2, 23, 43, 13, 88, 50, 45],
       [50, 63, 95, 46, 25, 41,  2, 15, 10, 63],
       [19, 32, 75, 86, 88, 73, 19, 86, 78, 12],
       [96, 48, 69, 70,  2, 96, 26, 87,  5, 34],
       [75, 58, 95, 89, 70, 97, 25, 32, 73, 23],
       [19, 24, 64, 84,  7, 76, 52, 71, 81, 97],
       [53, 89, 28, 59, 11, 60, 82, 19, 19, 90],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [208]:
arr=np.zeros((10,10))

In [210]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [212]:
arr[0]=1
arr[-1]=1

In [214]:
# arr[;,0:-1]
arr[:,0]=1
arr[:,-1]=1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr[]

In [177]:
arr2 = np.ones((10,10))

In [179]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [193]:
arr2[1:-1,1:-1]=0

In [195]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Checker board pattern

In [320]:
arr = np.random.randint(1,100,(8,8))

In [322]:
arr

array([[33, 25, 87,  6, 34, 83, 20, 66],
       [67,  5, 34, 80, 71,  3, 39, 82],
       [89, 46, 69, 22, 52, 66, 78, 37],
       [69, 29, 74,  2, 88,  7, 94, 15],
       [ 8, 27, 84, 12, 19, 21, 16, 87],
       [34, 15, 79, 11, 21, 47, 19, 33],
       [ 2,  8, 90, 18, 76, 39, 87, 37],
       [30, 72, 48, 62,  9, 60, 41, 99]])

In [324]:
arr[0][0:-1:2]=0

In [326]:
arr

array([[ 0, 25,  0,  6,  0, 83,  0, 66],
       [67,  5, 34, 80, 71,  3, 39, 82],
       [89, 46, 69, 22, 52, 66, 78, 37],
       [69, 29, 74,  2, 88,  7, 94, 15],
       [ 8, 27, 84, 12, 19, 21, 16, 87],
       [34, 15, 79, 11, 21, 47, 19, 33],
       [ 2,  8, 90, 18, 76, 39, 87, 37],
       [30, 72, 48, 62,  9, 60, 41, 99]])

In [328]:
arr[1][1:-1:2]=0
arr[2][0:-1:2]=0
arr[3][1:-1:2]=0
arr[4][0:-1:2]=0
arr[5][1:-1:2]=0
arr[6][0:-1:2]=0
arr[7][1:-1:2]=0

In [330]:
arr

array([[ 0, 25,  0,  6,  0, 83,  0, 66],
       [67,  0, 34,  0, 71,  0, 39, 82],
       [ 0, 46,  0, 22,  0, 66,  0, 37],
       [69,  0, 74,  0, 88,  0, 94, 15],
       [ 0, 27,  0, 12,  0, 21,  0, 87],
       [34,  0, 79,  0, 21,  0, 19, 33],
       [ 0,  8,  0, 18,  0, 39,  0, 37],
       [30,  0, 48,  0,  9,  0, 41, 99]])

In [405]:
b=np.zeros((8,8))

In [407]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [429]:
b[0:8:2, 1:8:2]=1


In [431]:
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [433]:
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [450]:
b[1:8:2, 0:8:2]=1

In [452]:
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [461]:
ex27 = np.random.rand(10)

In [463]:
ex27

array([0.39743843, 0.77606557, 0.41332726, 0.28910844, 0.32915868,
       0.39673715, 0.07021405, 0.34487931, 0.62123417, 0.38956916])

In [467]:
ex28= np.random.randn(10)

In [471]:
ex28

array([-0.52539725,  0.86163857, -0.48134721,  0.56703606,  1.28060385,
       -0.35558211,  0.96253882,  0.28537298, -1.25236562, -1.19826441])

In [473]:
np.sort(ex28)

array([-1.25236562, -1.19826441, -0.52539725, -0.48134721, -0.35558211,
        0.28537298,  0.56703606,  0.86163857,  0.96253882,  1.28060385])

In [476]:
ex29 = np.random.randn(10)

In [478]:
ex29

array([ 0.92923517, -1.62314696, -0.99930351,  1.13672069,  1.10034374,
        2.41853679, -1.02122814, -0.84369668,  0.16350061,  1.2963315 ])

In [503]:
x=np.argmax(ex29)

In [505]:
ex29[x]=0

In [507]:
ex29

array([ 0.92923517, -1.62314696, -0.99930351,  1.13672069,  1.10034374,
        0.        , -1.02122814, -0.84369668,  0.16350061,  1.2963315 ])

In [519]:
my_list = ['a', 'b', 'c']

for index, item in enumerate (my_list, 1):
    print(index, item)


1 a
2 b
3 c


In [615]:
b=np.arange(20)

In [617]:
b=b.reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [603]:
x=b[0]
b[0] = b[-1]


In [619]:
b[[0 , 3]] =b[[3 , 0]]

In [621]:
b

array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [16, 17, 18, 19]])

In [611]:
b

array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [16, 17, 18, 19]])

In [627]:
np.roll(b,)

TypeError: roll() missing 1 required positional argument: 'shift'

In [661]:
a=np.random.randint(1,10,5)
a

array([7, 9, 4, 5, 7])

In [669]:
np.bincount(a)

array([0, 0, 0, 0, 1, 1, 0, 2, 0, 1], dtype=int64)

In [671]:
np.bincount(a).argmax()

7

In [673]:
per = np.array([[56.0, 0.0, 4.4,  68.0],
       [1.2, 104.0, 52.0, 8.0],
       [1.8, 135.0, 99.0, 0.9]])

In [675]:
per

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [681]:
per.sum(axis=0)

array([ 59. , 239. , 155.4,  76.9])

In [693]:
print("For first item")
print(f'the percentage of carbs {(per[0][0]/ per.sum(axis=0)[0])*100}')
print(f' the percentage of proteins { (per[1][0]/per.sum(axis=0)[0])*100} ')
print(f' The percentage of fats { (per[2][0]/per.sum(axis=0)[0])*100}')

For first item
the percentage of carbs 94.91525423728814
 the percentage of proteins 2.0338983050847457 
 The percentage of fats 3.050847457627119


In [ ]:
print("For second item")
print(f'the percentage of carbs {(per[0][1]/ per.sum(axis=0)[1])*100}')
print(f' the percentage of proteins { (per[1][1]/per.sum(axis=0)[1])*100} ')
print(f' The percentage of fats { (per[2][1]/per.sum(axis=0)[1])*100}')

In [ ]:
print("For third item")
print(f'the percentage of carbs {(per[0][2]/ per.sum(axis=0)[2])*100}')
print(f' the percentage of proteins { (per[1][]/per.sum(axis=0)[0])*100} ')
print(f' The percentage of fats { (per[2][0]/per.sum(axis=0)[0])*100}')

In [701]:
t = per.sum(axis=1)
t

array([128.4, 165.2, 236.7])

In [707]:
per[0]/t[0] * 100

array([43.61370717,  0.        ,  3.42679128, 52.95950156])

In [709]:
per[1]/t[1] * 100

array([ 0.72639225, 62.95399516, 31.47699758,  4.84261501])

In [711]:
per[2]/t[2]  * 100

array([ 0.76045627, 57.03422053, 41.82509506,  0.38022814])