In [1]:
import numpy as np
a = np.array([1,2,44,5,6])
a *3


array([  3,   6, 132,  15,  18])

In [7]:
list1=[1,2,44,5,6]
list1*3

[1, 2, 44, 5, 6, 1, 2, 44, 5, 6, 1, 2, 44, 5, 6]

In [5]:
print(a)

[ 1  2 44  5  6]


## Using Numoy

In [9]:
import numpy as np

In [11]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [17]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones(((3,3,3)))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
import numpy as np
x = np.arange(6)
x = x.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
import numpy as np
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [39]:
np.zeros_like(y)

array([0., 0., 0.])

In [41]:
### Identity Matrix

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Basic Indexing with Numoy

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [49]:
np.linspace(10, 15, 5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [51]:
## 1D array indexing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [55]:
arr[4: 9]

array([4, 5, 6, 7, 8])

In [59]:
arr[4:9:2] = 100
arr

array([  0,   1,   2,   3, 100,   5, 100,   7, 100,   9])

In [61]:
arr

array([  0,   1,   2,   3, 100,   5, 100,   7, 100,   9])

In [63]:
arr26 = arr[2:6]
arr26[:] =26

In [65]:
arr
## Array slices are views on the original array, meaning any changes to the slice
## will reflect in the original array.

array([  0,   1,  26,  26,  26,  26, 100,   7, 100,   9])

In [67]:
arr2d = np.array([[0, 1, 2],
                 [3, 4, 5],
                 [6, 7, 8]])

In [69]:
result = arr2d[0:2, 1:3]
print(result)

[[1 2]
 [4 5]]


In [71]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
result1=arr2d[1:3, 0:3]
print(result1)

[[3 4 5]
 [6 7 8]]


In [79]:
result2=arr2d[0:1, 0:1]
print(result2)

[[0]]


In [84]:
result3 = arr2d[:]
print(result3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [86]:
result = arr2d[0:3:2]
print(result)

[[0 1 2]
 [6 7 8]]


In [88]:
result= arr2d[0:2, 2]
print(result)

[2 5]


In [90]:
arr2d = np.arange(9).reshape(3, 3)

In [92]:

arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr2d[0]

array([0, 1, 2])

In [96]:
arr2d [0][1]

1

In [98]:
arr2d[0, 1]

1

In [128]:
arr3d = np.random.rand(2,3,3 ,  3, 4)
arr3d

array([[[[[0.9067291 , 0.24228476, 0.50487547, 0.86156773],
          [0.36501771, 0.53066973, 0.57790534, 0.14145276],
          [0.95015578, 0.52114011, 0.84279687, 0.43277017]],

         [[0.09980379, 0.47528187, 0.24926092, 0.43610565],
          [0.02569258, 0.00575113, 0.89938549, 0.3471104 ],
          [0.31479467, 0.58676851, 0.30941493, 0.83290651]],

         [[0.93148505, 0.53434349, 0.21973928, 0.2516112 ],
          [0.97316816, 0.95863918, 0.94111686, 0.48240218],
          [0.33737959, 0.08928596, 0.39233397, 0.36033394]]],


        [[[0.86270202, 0.43769643, 0.59391031, 0.18711596],
          [0.56218409, 0.71436765, 0.65729411, 0.67204186],
          [0.08876515, 0.8218419 , 0.2685332 , 0.70152372]],

         [[0.71869202, 0.31910956, 0.74409662, 0.04659903],
          [0.36877896, 0.38792661, 0.65400477, 0.60904357],
          [0.15915635, 0.74494093, 0.32979395, 0.38306565]],

         [[0.14918645, 0.82089125, 0.1147283 , 0.91963141],
          [0.40549344, 0.053

In [118]:
arr3d[1]

array([[0.78329177, 0.87370518, 0.96361037, 0.04165903],
       [0.13175872, 0.88592562, 0.73650486, 0.13425634],
       [0.38201857, 0.06403769, 0.04039131, 0.87192604]])

In [120]:
arr3d[0]

array([[0.29547441, 0.60372568, 0.75553078, 0.74305504],
       [0.65508878, 0.93984627, 0.48032238, 0.03822654],
       [0.4316953 , 0.45357719, 0.26568522, 0.37641544]])

In [122]:
arr3d[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [124]:
arr3d[2]

array([[0.11775321, 0.97881201, 0.3818444 , 0.64845468],
       [0.10772673, 0.86744027, 0.35378323, 0.73329908],
       [0.85830338, 0.23114538, 0.3837709 , 0.56775338]])

## Important Attributes of Numpy Arrays

In [148]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [150]:
arr.dtype

dtype('int32')

In [154]:
np.__version__

'1.26.4'

In [164]:
f_arr = arr.astype(np.float64)
f_arr.dtype

dtype('float64')

In [170]:
a = np.array([[-0.3, 0.4, -1.4, -0.7, 0.2],
              [-1.0, -0.7, -0.3, 0.0, -0.5],
              [0.05, -0.02, -0.3, -0.25, -0.2]])

a.shape
# Output: (3, 5)

(3, 5)

In [174]:
b=a.reshape(1, 15)


In [178]:
b.shape

(1, 15)

In [180]:
a.reshape(15,1)

array([[-0.3 ],
       [ 0.4 ],
       [-1.4 ],
       [-0.7 ],
       [ 0.2 ],
       [-1.  ],
       [-0.7 ],
       [-0.3 ],
       [ 0.  ],
       [-0.5 ],
       [ 0.05],
       [-0.02],
       [-0.3 ],
       [-0.25],
       [-0.2 ]])

In [182]:
a

array([[-0.3 ,  0.4 , -1.4 , -0.7 ,  0.2 ],
       [-1.  , -0.7 , -0.3 ,  0.  , -0.5 ],
       [ 0.05, -0.02, -0.3 , -0.25, -0.2 ]])

## Boolean Indexing

In [9]:
import numpy as np

boolean_arr = np.array([True, False, False]*3)

arr = np.arange(9)

result = arr[boolean_arr]
print(result)


[0 3 6]


In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr%2==0

array([ True, False,  True, False,  True, False,  True, False,  True])

In [15]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [17]:
arr = np.random.randn(5, 2)
print("Original array:\n", arr)

arr[arr<0] = 0

print("\nArray after replacing negatives with 0:\n", arr)

Original array:
 [[-0.23041599  1.7032806 ]
 [-0.12136525  2.03634283]
 [-1.58511119  0.66775554]
 [ 0.65153394 -0.07538236]
 [-2.06662065  1.15570601]]

Array after replacing negatives with 0:
 [[0.         1.7032806 ]
 [0.         2.03634283]
 [0.         0.66775554]
 [0.65153394 0.        ]
 [0.         1.15570601]]


In [19]:
arr

array([[0.        , 1.7032806 ],
       [0.        , 2.03634283],
       [0.        , 0.66775554],
       [0.65153394, 0.        ],
       [0.        , 1.15570601]])

## Descriptive Methods in Numpy

In [27]:
a = np.random.randn(3, 5)
a

array([[-0.15606807, -1.77975722, -0.57969971, -1.38389676, -0.71006029],
       [-0.94199887,  0.92824734, -0.83871456, -1.54769946, -0.69043835],
       [-2.64194638, -0.1559693 , -1.38968478, -0.45211128,  1.40140701]])

In [31]:
mean_value = a.mean()
mean_value_np = np.mean(a)
print(mean_value, mean_value_np)

-0.7292260462267107 -0.7292260462267107


In [39]:
print(a.shape)


mean_axis1 = a.mean(axis=1)
print(mean_axis1)

sum_axis0 = a.sum(axis=0)
print(sum_axis0)

(3, 5)
[-0.92189641 -0.61812078 -0.64766095]
[-3.74001332e+00 -1.00747918e+00 -2.80809906e+00 -3.38370750e+00
  9.08372317e-04]


In [41]:
mean_axis1.shape

(3,)

In [48]:
sum_axis0.shape

(5,)

## Conditional Logic

In [52]:
x = np.arange(5)
y = np.arange(5, 10)

cond = np.array([True, False, True, False, False])

result = np.where(cond, x, y)  ## np.where x if condition else y in python
print(result)

[0 6 2 8 9]


In [54]:
arr = np.random.randn(10)
print(arr)


result = np.where(arr>0,True, False)
print(result)

[-1.18844729  0.57224779 -0.18303994 -0.01527877 -0.40211194  2.06608001
 -0.83983571 -1.16613812  0.1332848  -1.35746557]
[False  True False False False  True False False  True False]


In [66]:
cond1 = np.array([True, False, True, True, False, False, False])
cond2 = np.array([True, False, True, False, False, True, False])

result= []

for i in range(len(cond1)):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [62]:
print(result)

[0, 3, 0, 1, 3, 2, 3]


In [68]:
result = np.where(cond1 & cond2, 0,
                  np.where(cond1, 1,
                          np.where(cond2, 2, 3)))

In [70]:
print(result)

[0 3 0 1 3 2 3]


In [72]:
result = np.where(cond1 & cond2,0 ,np.where(cond1, 1, np.where(cond2, 2, 3)))

In [74]:
print(result)

[0 3 0 1 3 2 3]


## Arithmetic operators in numpy
Arrays in NumPy enable batch operations on data without the need for explicit loops, a feature known as vectorization. Here’s how arithmetic operations work:

## 1. Element-wise Operations
When you perform arithmetic operations between equal-size arrays, NumPy applies the operation element-wise.

In [97]:
import numpy as np

arr = np.arange(10)
print(arr)

##Array multiplication

print(arr * arr)

## array division
print(arr)
print(arr / arr)   ## nan not a number when 0/0

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 2 3 4 5 6 7 8 9]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Prasad\AppData\Local\Temp\ipykernel_12524\3824922387.py:12: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)   ## nan not a number when 0/0


## Scalar Operations
When performing arithmetic with scalars, the scalar value is applied to each element of the array.

In [100]:
print(1 / arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\Prasad\AppData\Local\Temp\ipykernel_12524\1255350848.py:1: RuntimeWarning: divide by zero encountered in divide
  print(1 / arr)


## Broadcasting

## 1)Scalar Broadcasting

In [104]:
import numpy as np

arr = np.arange(10)
print(arr)
print(arr * 2)


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


## Demeaning an Array

## Demeanin g columns

In [121]:
arr = np.random.randn(5, 4)
column_means = arr.mean(axis=0)
demeaned = arr - column_means
print(arr)
print(column_means)

[[ 1.11133614  0.89304228  0.46663585  1.03555299]
 [ 0.64605384  0.84516142 -0.2668968   0.73715157]
 [ 0.74992268 -0.57507603  0.73558259 -0.21104345]
 [-0.85944627  0.08243408  0.69961015 -0.71834014]
 [-1.35005888  0.00743668 -0.97764818 -0.63968753]]
[0.0595615  0.25059969 0.13145672 0.04072669]


In [123]:
print(demeaned)

[[ 1.05177464  0.64244259  0.33517913  0.9948263 ]
 [ 0.58649234  0.59456173 -0.39835353  0.69642488]
 [ 0.69036117 -0.82567571  0.60412587 -0.25177014]
 [-0.91900777 -0.16816561  0.56815343 -0.75906682]
 [-1.40962038 -0.24316301 -1.1091049  -0.68041422]]


## Demeaning Rows

In [155]:
row_means = arr.mean(axis=1).reshape(5,1)
print(row_means)
demeaned_rows = arr - row_means

[[ 0.87664181]
 [ 0.49036751]
 [ 0.17484645]
 [-0.19893554]
 [-0.73998948]]


In [144]:
print(demeaned_rows)

[[ 0.23469432  0.01640047 -0.41000596  0.15891117]
 [ 0.15568633  0.35479391 -0.75726431  0.24678406]
 [ 0.57507623 -0.74992247  0.56073615 -0.3858899 ]
 [-0.66051073  0.28136963  0.8985457  -0.51940459]
 [-0.6100694   0.74742616 -0.2376587   0.10030195]]


In [146]:
demeaned_rows.shape



(5, 4)

In [148]:
row_means.shape

(5, 1)

In [150]:
print(arr.mean(axis=1))

[ 0.87664181  0.49036751  0.17484645 -0.19893554 -0.73998948]


In [161]:
import numpy as np

arr = np.random.randn(5, 4)

row_means = arr.mean(axis=1).reshape(5, 1)


demeaned_rows = arr - row_means


print("Original Array:\\n", arr)
print("\\nRow means:\\n", row_means)
print("\\nDemeaned Rows:\\n", demeaned_rows)
print("\\nMean of demeaned Rows:\\n", demeaned_rows.mean(axis=1))

Original Array:\n [[-0.69695659 -1.37244758 -0.06041725 -0.66265645]
 [-0.61764856  1.38137586 -0.05552733  0.90919162]
 [ 0.45277551 -0.21259348  0.02676951 -0.89159958]
 [ 0.31942808 -1.50634098 -1.30625621 -0.40569798]
 [ 1.2098334  -0.87994375 -1.18358261  1.05300795]]
\nRow means:\n [[-0.69811947]
 [ 0.4043479 ]
 [-0.15616201]
 [-0.72471677]
 [ 0.04982875]]
\nDemeaned Rows:\n [[ 1.16287546e-03 -6.74328113e-01  6.37702221e-01  3.54630169e-02]
 [-1.02199645e+00  9.77027962e-01 -4.59875226e-01  5.04843718e-01]
 [ 6.08937515e-01 -5.64314662e-02  1.82931518e-01 -7.35437566e-01]
 [ 1.04414485e+00 -7.81624207e-01 -5.81539438e-01  3.19018795e-01]
 [ 1.16000465e+00 -9.29772497e-01 -1.23341136e+00  1.00317921e+00]]
\nMean of demeaned Rows:\n [ 5.55111512e-17  2.77555756e-17  0.00000000e+00 -4.16333634e-17
 -5.55111512e-17]


## Tips and Tricks

In [247]:
arrw= np.random.randn(5,2)
print(arrw)
meanaxis0=arrw.mean(axis=0)
print(meanaxis0)
print(meanaxis0.shape)

[[ 1.66694281 -0.65370912]
 [ 0.00828269 -0.89866076]
 [ 0.44107421  0.29449629]
 [-0.26393964  0.39246586]
 [ 0.40681729  0.21084747]]
[ 0.45183547 -0.13091205]
(2,)


In [257]:
arrq = np.random.rand(4,5,2)
print(arrq)
mean_axis_0= arrq.mean(axis=0)
mean_axis_1= arrq.mean(axis=1)
mean_axis_2=arrq.mean(axis=2)


print(mean_axis_0)
print(mean_axis_0.shape)

print(mean_axis_1)
print(mean_axis_1.shape)

print(mean_axis_2)
print(mean_axis_2.shape)

[[[0.49798435 0.2516971 ]
  [0.26860827 0.25847868]
  [0.79882958 0.09774321]
  [0.94046465 0.65045319]
  [0.55068847 0.4732957 ]]

 [[0.91387297 0.07477381]
  [0.04973932 0.74437692]
  [0.49009264 0.33404915]
  [0.5626313  0.60040937]
  [0.50651372 0.04360775]]

 [[0.39152263 0.51169358]
  [0.0827378  0.83393528]
  [0.2744116  0.95610843]
  [0.01096763 0.80570691]
  [0.03024086 0.45186021]]

 [[0.29317721 0.35841931]
  [0.85075941 0.81467555]
  [0.31600775 0.16168166]
  [0.69869199 0.73954955]
  [0.15924305 0.28111444]]]
[[0.52413929 0.29914595]
 [0.3129612  0.66286661]
 [0.46983539 0.38739561]
 [0.55318889 0.69902975]
 [0.31167153 0.31246953]]
(5, 2)
[[0.61131506 0.34633358]
 [0.50456999 0.3594434 ]
 [0.1579761  0.71186088]
 [0.46357588 0.4710881 ]]
(4, 2)
[[0.37484072 0.26354348 0.44828639 0.79545892 0.51199209]
 [0.49432339 0.39705812 0.4120709  0.58152033 0.27506074]
 [0.45160811 0.45833654 0.61526002 0.40833727 0.24105053]
 [0.32579826 0.83271748 0.2388447  0.71912077 0.22017875]

In [233]:
import numpy as np

arr4d = np.random.randn(4,3, 5, 2)
# print(arr4d)
print("mean",arr4d.mean())
print("mean axis 0",arr4d.mean(axis=1).shape)
# print("mean axis 1", arr4d.mean(axis=1))
# print("mean axis 2", arr4d.mean(axis=2))
# print("mean axis 3", arr4d.mean(axis=3))

mean -0.01025375617986617
mean axis 0 (4, 5, 2)


In [166]:
print(arr4d.mean().shape)
print(arr4d.mean(axis=0).shape)
print(arr4d.mean(axis=1).shape)
print(arr4d.mean(axis=2).shape)
print(arr4d.mean(axis=3).shape)

()
(4, 5, 2)
(3, 5, 2)
(3, 4, 2)
(3, 4, 5)


## Demeaning a 3d array

In [203]:
arr3d = np.random.randn(4, 3, 2)
print(arr3d)

[[[ 0.83332354  0.589728  ]
  [ 1.00549353  0.9290913 ]
  [ 0.06274174  0.59057923]]

 [[-0.8109775   0.69723334]
  [-0.13664057  0.06753651]
  [-0.52591723 -0.08353847]]

 [[-1.21166488 -2.02348942]
  [-0.45007034  0.61421809]
  [-0.15674293 -0.4374894 ]]

 [[-1.48417849 -2.06594387]
  [-0.47795487 -1.30994967]
  [ 0.53881901  1.93253289]]]


In [237]:
demeaned_axis0 = arr3d - arr3d.mean(axis=0)
print("Demeaned along axis 0 shape:", demeaned_axis.shape)

demeaned_axis1 = arr3d - arr3d.mean(axis=1, keepdims=True)
print("Demeaned along axis 1 shape:", demeaned_axis1.shape)

demeaned_axis2 = arr3d - arr3d.mean(axis=2, keepdims=True)
print("Demeaned along axis 2 shape:", demeaned_axis2.shape)

NameError: name 'demeaned_axis' is not defined

In [197]:
arr3d#.mean(axis=2, keepdims=True)

array([[-0.4624281 ,  0.63132783],
       [ 0.23833928, -0.38975102],
       [ 0.35520486, -0.45144423]])

In [185]:
# Demeaning across axis 0
demeaned_axis0 = arr3d - arr3d.mean(axis=0)
print("Demeaned along axis 0 shape:", demeaned_axis0.shape)

# Demeaning across axis 1
demeaned_axis1 = arr3d - arr3d.mean(axis=1, keepdims=True)
print("Demeaned along axis 1 shape:", demeaned_axis1.shape)

# Demeaning across axis 2
demeaned_axis2 = arr3d - arr3d.mean(axis=2, keepdims=True)
print("Demeaned along axis 2 shape:", demeaned_axis2.shape)

Demeaned along axis 0 shape: (3, 2)
Demeaned along axis 1 shape: (3, 2)


AxisError: axis 2 is out of bounds for array of dimension 2

In [7]:
import numpy as np

arr=np.random.randn(5,2)
print(arr)
print(arr.mean(axis=0))
print(arr.mean(axis=1))

[[-1.15366305  0.2904895 ]
 [ 0.62660534  1.02758385]
 [ 0.17282931  1.2918722 ]
 [ 1.95224784 -0.29005794]
 [-1.67821559  0.5731251 ]]
[-0.01603923  0.57860254]
[-0.43158677  0.82709459  0.73235076  0.83109495 -0.55254524]


In [13]:
arr = np.random.randn(4, 5, 2)
print(arr)
print("Next axis = 0")
print(arr.mean(axis=0))

print("Next axis =1")
print(arr.mean(axis=1))

print("Next axis =2")
print(arr.mean(axis=2))

[[[-0.6420464   1.03481319]
  [-1.19619292 -0.82656269]
  [-1.56459825 -0.98591935]
  [-0.62499202 -1.414061  ]
  [-0.72530714  1.29613981]]

 [[ 0.66000587 -0.09696377]
  [-1.49910407  0.04630788]
  [ 2.19910095  0.08384324]
  [-0.4377011   0.40034685]
  [ 0.48543497  0.40770485]]

 [[ 0.53564794 -0.16142527]
  [ 1.20549501 -2.49413357]
  [ 0.66865559  0.80631406]
  [ 0.69208582 -1.01862356]
  [-2.0965025  -0.25847853]]

 [[ 1.33862585 -1.23048992]
  [ 1.12874381 -0.14520198]
  [ 0.55990272 -0.51338662]
  [-0.34413785  0.39308482]
  [-0.29265568  2.47038699]]]
Next axis = 0
[[ 0.47305832 -0.11351644]
 [-0.09026454 -0.85489759]
 [ 0.46576525 -0.15228717]
 [-0.17868629 -0.40981322]
 [-0.65725759  0.97893828]]
Next axis =1
[[-0.95062734 -0.17911801]
 [ 0.28154733  0.16824781]
 [ 0.20107637 -0.62526937]
 [ 0.47809577  0.19487866]]
Next axis =2
[[ 0.1963834  -1.0113778  -1.2752588  -1.01952651  0.28541633]
 [ 0.28152105 -0.7263981   1.1414721  -0.01867712  0.44656991]
 [ 0.18711134 -0.6443