## Numpy provides convinient functions for saving and loading arrays in both binary and textformats.

In [6]:
import numpy as np

arr = np.random.randn(10, 5)

np.save("file_arr", arr)

In [14]:
loaded_arr = np.load('file_arr.npy')
print(loaded_arr)

[[ 0.69161215  1.47651619 -1.04673937  2.17673775 -0.43087566]
 [ 0.07829762 -0.31935773 -0.82240971  0.57496122 -0.91359397]
 [-0.09151611  1.10259487  3.32446434 -1.09505354 -1.13310115]
 [-0.58709458 -2.62862957 -0.6684413  -0.98827803 -0.02323601]
 [-0.79247259  1.69840127  2.43334697 -0.26505298 -0.9290274 ]
 [-0.5587992  -0.63421508 -0.31033981 -0.59019811 -0.05664631]
 [ 0.044198    2.39772707 -1.55871841 -1.30190091 -0.72596984]
 [-0.27532803  1.68524695  1.26010875  0.65787852  0.05307881]
 [ 0.26786325  1.48173479 -1.3206255  -1.34579896 -0.5623491 ]
 [-0.21595485 -0.86065967  0.58942824 -1.07280232 -0.74630147]]


In [16]:
np.savez('file_arr', a=arr, b=arr)

In [18]:
arrs = np.load('file_arr.npz')
print(arrs)

NpzFile 'file_arr.npz' with keys: a, b


In [20]:
print(arrs['a'])

[[ 0.69161215  1.47651619 -1.04673937  2.17673775 -0.43087566]
 [ 0.07829762 -0.31935773 -0.82240971  0.57496122 -0.91359397]
 [-0.09151611  1.10259487  3.32446434 -1.09505354 -1.13310115]
 [-0.58709458 -2.62862957 -0.6684413  -0.98827803 -0.02323601]
 [-0.79247259  1.69840127  2.43334697 -0.26505298 -0.9290274 ]
 [-0.5587992  -0.63421508 -0.31033981 -0.59019811 -0.05664631]
 [ 0.044198    2.39772707 -1.55871841 -1.30190091 -0.72596984]
 [-0.27532803  1.68524695  1.26010875  0.65787852  0.05307881]
 [ 0.26786325  1.48173479 -1.3206255  -1.34579896 -0.5623491 ]
 [-0.21595485 -0.86065967  0.58942824 -1.07280232 -0.74630147]]


In [22]:
print(arrs['b'])

[[ 0.69161215  1.47651619 -1.04673937  2.17673775 -0.43087566]
 [ 0.07829762 -0.31935773 -0.82240971  0.57496122 -0.91359397]
 [-0.09151611  1.10259487  3.32446434 -1.09505354 -1.13310115]
 [-0.58709458 -2.62862957 -0.6684413  -0.98827803 -0.02323601]
 [-0.79247259  1.69840127  2.43334697 -0.26505298 -0.9290274 ]
 [-0.5587992  -0.63421508 -0.31033981 -0.59019811 -0.05664631]
 [ 0.044198    2.39772707 -1.55871841 -1.30190091 -0.72596984]
 [-0.27532803  1.68524695  1.26010875  0.65787852  0.05307881]
 [ 0.26786325  1.48173479 -1.3206255  -1.34579896 -0.5623491 ]
 [-0.21595485 -0.86065967  0.58942824 -1.07280232 -0.74630147]]


In [24]:
np.savetxt('file_arr',arr,delimiter=',')

In [28]:
arr_from_txt = np.loadtxt('file_arr',delimiter=',')
print(arr_from_txt)

[[ 0.69161215  1.47651619 -1.04673937  2.17673775 -0.43087566]
 [ 0.07829762 -0.31935773 -0.82240971  0.57496122 -0.91359397]
 [-0.09151611  1.10259487  3.32446434 -1.09505354 -1.13310115]
 [-0.58709458 -2.62862957 -0.6684413  -0.98827803 -0.02323601]
 [-0.79247259  1.69840127  2.43334697 -0.26505298 -0.9290274 ]
 [-0.5587992  -0.63421508 -0.31033981 -0.59019811 -0.05664631]
 [ 0.044198    2.39772707 -1.55871841 -1.30190091 -0.72596984]
 [-0.27532803  1.68524695  1.26010875  0.65787852  0.05307881]
 [ 0.26786325  1.48173479 -1.3206255  -1.34579896 -0.5623491 ]
 [-0.21595485 -0.86065967  0.58942824 -1.07280232 -0.74630147]]
