## Numpy gives us a set of universal functions which gives us ability to operate element wise

Three types
1) unary ufuncs
2) binary ufuncs
3) aggregate functions

In [4]:
import numpy as np

np.abs(-1.0435)

1.0435

In [6]:
np.abs(124122412.13414124)

124122412.13414124

In [12]:
np.fabs(12124124 i-287465287)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (7808907.py, line 1)

In [14]:
np.sqrt(25)

5.0

mp.square(3)

In [17]:
np.square(3)

9

In [19]:
np.exp(3)

20.085536923187668

In [23]:
np.log(2)

0.6931471805599453

In [25]:
np.sign(-13414.24124)

-1.0

In [27]:
np.sign(13413)

1

In [29]:
np.sign(0)

0

In [37]:
arr=np.random.randn(3,3)
np.sqrt(arr)

C:\Users\Prasad\AppData\Local\Temp\ipykernel_15228\3444610929.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[0.22823364, 0.4977071 ,        nan],
       [       nan,        nan, 0.27470077],
       [       nan, 0.16297264, 0.60407946]])

In [41]:
x=np.array([[1.0, 1.41421356, 1.73205081, 2.0],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.0, 3.16227766, 3.31662479, 3.46410162]])
x

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [43]:
arr

array([[ 0.05209059,  0.24771236, -1.16368533],
       [-0.93464285, -0.21897307,  0.07546052],
       [-0.21467078,  0.02656008,  0.36491199]])

In [45]:
np.exp(arr)

array([[1.05347118, 1.28109139, 0.31233301],
       [0.3927261 , 0.80334335, 1.07838065],
       [0.80680701, 1.02691594, 1.44038723]])

In [47]:
np.sqrt(arr)

C:\Users\Prasad\AppData\Local\Temp\ipykernel_15228\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[0.22823364, 0.4977071 ,        nan],
       [       nan,        nan, 0.27470077],
       [       nan, 0.16297264, 0.60407946]])

In [49]:
np.log(arr)

C:\Users\Prasad\AppData\Local\Temp\ipykernel_15228\3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[-2.9547709 , -1.39548704,         nan],
       [        nan,         nan, -2.58414573],
       [        nan, -3.62834586, -1.00809908]])

In [51]:
arr1=np.random.randn(4,4)
arr2=np.random.randn(4,4)
print(arr1)
print(arr2)

[[-1.25149673  0.85943627  0.55526232 -0.23803436]
 [ 1.87923379 -0.64278236 -0.21699171  0.13672664]
 [-0.85971988 -2.02190423  0.40798598 -1.80695862]
 [-0.85129979  0.09088309 -1.35106026 -1.05127217]]
[[-0.72628782  0.08321249 -0.56461976 -1.61057267]
 [-0.69804724  1.44054757  0.05930639  0.85524385]
 [-0.32004909 -1.14671366  1.59911559 -1.68275018]
 [ 0.8501991  -0.29578821 -1.02724653  2.05158061]]


In [53]:
np.add(arr1, arr2)

array([[-1.97778455e+00,  9.42648755e-01, -9.35744196e-03,
        -1.84860703e+00],
       [ 1.18118655e+00,  7.97765209e-01, -1.57685324e-01,
         9.91970495e-01],
       [-1.17976897e+00, -3.16861789e+00,  2.00710157e+00,
        -3.48970880e+00],
       [-1.10069337e-03, -2.04905119e-01, -2.37830679e+00,
         1.00030844e+00]])

In [55]:
np.subtract(arr1, arr2)

array([[-0.52520891,  0.77622378,  1.11988208,  1.37253832],
       [ 2.57728102, -2.08332992, -0.2762981 , -0.71851721],
       [-0.53967079, -0.87519057, -1.1911296 , -0.12420843],
       [-1.70149889,  0.3866713 , -0.32381374, -3.10285279]])

In [57]:
np.multiply(arr1, arr2)

array([[ 0.90894683,  0.07151583, -0.31351208,  0.38337163],
       [-1.31179395, -0.92595856, -0.01286899,  0.11693462],
       [ 0.27515257,  2.3185452 ,  0.65241675,  3.04065994],
       [-0.72377432, -0.02688215,  1.38787197, -2.15676961]])

In [59]:
np.divide(arr1, arr2)

array([[ 1.72314157, 10.32821235, -0.983427  ,  0.14779486],
       [-2.69212982, -0.44620696, -3.65882531,  0.15986861],
       [ 2.68621252,  1.76321631,  0.25513227,  1.07381276],
       [-1.00129463, -0.30725731,  1.31522495, -0.5124206 ]])

In [61]:
np.sum(arr)

-1.7652364917514474

In [63]:
np.mean(arr)

-0.19613738797238303

In [65]:
np.std(arr)

0.49206594146966637